pipeline {
    agent any
stages {
  stage('Checkout') {
    steps {
        git branch: 'main', url: 'https://github.com/luggichi/Jenkins_test.git'
        echo '---Checkout'
    }
  }
  stage('Build') {
      steps {
        echo '---Building'
      }
  }
  stage('Test') {
    steps{
        echo '---Testing'
    }
  }
}
post{
    always{
        script {
            withEnv([
                "LOKAL=C:\\Daten_Engelhardt\\Abschlussarbeit_demo\\demo_${BUILD_NUMBER}"
            ]) {
                junit allowEmptyResults: true, healthScaleFactor: 0.0, testResults: 'Abschlussarbeit_demo/demo.xml'
                        publishHTML target: [
                            allowMissing: true,
                            alwaysLinkToLastBuild: false,
                            keepAll: true,
                            reportDir: 'Abschlussarbeit_demo',
                            reportFiles: 'demo.txt',
                            reportName: 'Testreport'
                        ]
                try {
                    bat """
                        if not exist "${LOKAL}" mkdir ${LOKAL}
                        echo create artifactory: > ${LOKAL}\\build.txt
                        echo ${params.TEST} >> ${LOKAL}\\build.txt
                        """
                    } catch (Exception ex) {
                        println("Caught an exception");
                    }            
                }
            }
        } 
    }
}
